namespace SportfyRevit
{
    /// <summary>
    /// What Revit's English template (Templates\English\Default-Multi-Discipline_Metric.rte) brings into a project: 40 view templates, 29 filters, 14 schedules, 22 sheets, 30 views.
    /// GENERATED by Tools/templates/generate-builtin-set.js from TemplateInspector's inspection of the template: do not edit. "Hide Revit templates" removes these from a Sportify project
    /// (only the ones nothing of the user's uses) and "Show Revit templates" copies them back from the template file.
    /// </summary>
    internal static class BuiltInEnglishTemplate
    {
        /// <summary>Path of the template below Revit's Templates folder.</summary>
        public const string TemplateFile = "English\\Default-Multi-Discipline_Metric.rte";

        public static readonly string[] ViewTemplates =
        {
            "Analytical Model with Local Coordinate System displayed",
            "Architectural Elevation",
            "Architectural Plan",
            "Architectural Presentation 3D",
            "Architectural Presentation Elevation",
            "Architectural Reflected Ceiling Plan",
            "Architectural Section",
            "Electrical Ceiling",
            "Electrical Elevation",
            "Electrical Lighting Plan",
            "Electrical Plan",
            "Electrical Power Plan",
            "Electrical Section",
            "Export to Civil Engineering",
            "Mechanical Ceiling",
            "Mechanical Elevation",
            "Mechanical Plan",
            "Mechanical Section",
            "Plumbing Ceiling",
            "Plumbing Elevation",
            "Plumbing Plan",
            "Plumbing Section",
            "Schedule Typical",
            "Schedule Working",
            "Site Plan",
            "Site Section",
            "Structural Analytical Isolated",
            "Structural Analytical Isolated-3D",
            "Structural Analytical Unconnected Nodes",
            "Structural Building Elevation",
            "Structural Connections-ApprovalStatus",
            "Structural Drafting View",
            "Structural Foundation Plan",
            "Structural Framing Elevation",
            "Structural Framing Plan",
            "Structural Model & Analytical Combined",
            "Structural Section",
            "Working Plans",
            "Working View",
            "Working Views - Override",
        };

        public static readonly string[] Filters =
        {
            "ABL - General Lighting",
            "ABL - General Power",
            "Domestic Cold Water",
            "Domestic Hot Water",
            "Domestic",
            "Floors - Concrete NOT",
            "Floors - Deck",
            "Floors - Finish",
            "Floors - Generic",
            "Generic Models - Openings NOT",
            "Hydronic",
            "Interior",
            "Levels - Building",
            "Levels - Structural",
            "MEP - System Classification",
            "Mechanical - Exhaust",
            "Mechanical - Return",
            "Mechanical - Supply",
            "Roofs - Generic",
            "Sanitary",
            "Structrual - Size",
            "Structural Columns Framing - Concrete NOT",
            "Structural Columns Framing - Concrete",
            "Structural Framing - Series",
            "Structural Framing - Z Offset",
            "Vent",
            "Views - Working",
            "Walls - Concrete NOT",
            "Walls - Sweeps",
        };

        public static readonly string[] Schedules =
        {
            "Door Schedule",
            "Electrical Analytical Bus Schedule",
            "Electrical Analytical Load Schedule",
            "Level Schedule",
            "Room Finish Schedule",
            "Sheet Index",
            "Space Outdoor Air Schedule",
            "Structural Column Schedule",
            "Structural Foundation Schedule",
            "Structural Framing Schedule",
            "Structural Wall Schedule",
            "Window Schedule",
            "Working_Sheet List",
            "Working_View List",
        };

        public static readonly string[] SheetNumbers =
        {
            "A101",
            "A102",
            "A201",
            "A202",
            "A203",
            "A204",
            "A301",
            "A401",
            "A501",
            "A601",
            "C101",
            "E101",
            "E102",
            "E103",
            "E104",
            "G100",
            "M101",
            "M102",
            "P101",
            "P102",
            "S101",
            "S102",
        };

        /// <summary>"ViewType|Name" of each view.</summary>
        public static readonly string[] Views =
        {
            "CeilingPlan|L1 - Architectural",
            "CeilingPlan|L1 - Lighting",
            "CeilingPlan|L1 - Mechanical",
            "CeilingPlan|L2 - Architectural",
            "CeilingPlan|L2 - Lighting",
            "CeilingPlan|L2 - Mechanical",
            "Elevation|East - Architectural",
            "Elevation|North - Architectural",
            "Elevation|South - Architectural",
            "Elevation|West - Architectural",
            "EngineeringPlan|L1 - Structural",
            "EngineeringPlan|L2 - Structural",
            "FloorPlan|L1 - Architectural",
            "FloorPlan|L1 - Lighting",
            "FloorPlan|L1 - Mechanical",
            "FloorPlan|L1 - Plumbing",
            "FloorPlan|L1 - Power",
            "FloorPlan|L1 - Working",
            "FloorPlan|L2 - Architectural",
            "FloorPlan|L2 - Lighting",
            "FloorPlan|L2 - Mechanical",
            "FloorPlan|L2 - Plumbing",
            "FloorPlan|L2 - Power",
            "FloorPlan|L2 - Working",
            "FloorPlan|Site",
            "Legend|Symbols",
            "Legend|Text and Dimensions",
            "Section|Section 1",
            "ThreeD|Cover Sheet View",
            "ThreeD|{3D}",
        };
    }
}
